### ISSUE TITLE
Include in Theme

### ISSUE THREAD

**Issue by troytempleman** [joppuyo/html-markup-indenter#2]
This is great, I've been looking for something like this for awhile. This is not an issue but I'm trying to include into a theme instead of a plugin by replacing:

`require 'library/dindent/src/Indenter.php';`

with 

`require get_template_directory() . '/inc/html-markup-indenter/library/dindent/src/Indenter.php';`

However, it doesn't work. Any thoughts?

**Comment by joppuyo** [comment]
Hi, this plugin is intended to be used standalone plugin and not as part of a theme. However, I looked into this and it seems that `plugins_loaded` hook is not fired if it's inside a theme and not a plugin. This hook is used because it's earliest hook in WP lifecycle so we use it to start the output buffer.

I managed to get the indentation working inside a theme by changing the hook `plugins_loaded` to `init` [on on this line](https://github.com/joppuyo/html-markup-indenter/blob/39de4965813ea26c1435ddfb8a8e38d8065ae6f3/html-markup-indenter.php#L18). 

Other thing, you should not be requiring the **Dindent library** in your theme, instead require the **plugin itself** by calling `require 'inc/html-markup-indenter/html-markup-indenter.php';` in your theme. This will require the theme which will then require the required plugin.

I hope this helps!

**Comment by troytempleman** [comment]
Thanks, that worked like a charm!

**Comment by joppuyo** [comment]
Great, glad you got it working in your case!
